name: DeletedItems
author: BlackAsLight
main: com.stagintin.deleteditems.Main
version: 0.0.6
api-version: 1.17
description: A plugin that catches deleted items.
commands:
  beep:
    description: Responds with Boop
  di:
    aliases: [deleteditems]
    description: Opens up the Shop Inventory
