name: DeletedItems
author: BlackAsLight
main: com.stagintin.deleteditems.Main
version: 1.1.0
api-version: 1.17
description: A plugin that catches deleted items.
commands:
  di:
    aliases: [deleteditems]
    description: Opens up the Shop Inventory
